### ISSUE TITLE
Drive content not updating when switching Nodes

### ISSUE THREAD

**Issue by carlaost** [desci-labs/dpid-fetch#7]
this is fixed by refreshing. i did just publish v2 of the node whose drive we keep seeing, maybe that's related?

[Private Zenhub Video](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNXBZQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--e2c3a6afdd6f34446fbe1b8884c191efb901ebec/Kapture%202023-10-20%20at%2011.01.10.mp4)

**Comment by hubsmoke** [comment]
should be fixed
